// <auto-generated />
using FoodECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250517171021_RemoveImageAndDescriptionFromRestaurant")]
    partial class RemoveImageAndDescriptionFromRestaurant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodECommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = "menüler.png",
                            Name = "Menus"
                        },
                        new
                        {
                            Id = 2,
                            ImageName = "burgers.png",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 3,
                            ImageName = "tatlılar.png",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            ImageName = "içecekler.png",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 5,
                            ImageName = "soslar.png",
                            Name = "Sauces"
                        },
                        new
                        {
                            Id = 6,
                            ImageName = "kids.png",
                            Name = "Kids Menu"
                        });
                });

            modelBuilder.Entity("FoodECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lezzetli tavuk burger menüsü.",
                            ImageUrl = "images/products/chickenroyalemenü.png",
                            Name = "Chicken Royale Menü",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lezzetli tavuk burger menüsü.",
                            ImageUrl = "images/products/tavukburgermenü.png",
                            Name = "Tavuk Burger Menü",
                            Price = 215m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Baharatlı menü seçeneği.",
                            ImageUrl = "images/products/spicymenü.png",
                            Name = "Spicy Menü",
                            Price = 230m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Klasik burger.",
                            ImageUrl = "images/products/whopper.png",
                            Name = "Whopper",
                            Price = 155m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Barbekü soslu burger.",
                            ImageUrl = "images/products/rodeo.png",
                            Name = "Rodeo Burger",
                            Price = 135m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Tavuk burger.",
                            ImageUrl = "images/products/tavuklu.png",
                            Name = "Tavuklu Burger",
                            Price = 120m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "Ballı hardal sos.",
                            ImageUrl = "images/products/ballımustrad.png",
                            Name = "Ball Mustard",
                            Price = 6m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Description = "Klasik ketçap.",
                            ImageUrl = "images/products/ketçap.png",
                            Name = "Ketçap",
                            Price = 6m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Klasik mayonez.",
                            ImageUrl = "images/products/mayonez.png",
                            Name = "Mayonez",
                            Price = 6m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Soslu dondurma.",
                            ImageUrl = "images/products/sundae.png",
                            Name = "Sundae",
                            Price = 45m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Kurabiye",
                            ImageUrl = "images/products/cookie.png",
                            Name = "Cookie",
                            Price = 45m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = " Kola",
                            ImageUrl = "images/products/cocacola.png",
                            Name = "Coca-Cola",
                            Price = 40m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Fanta",
                            ImageUrl = "images/products/fanta.png",
                            Name = "Fanta",
                            Price = 40m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Sıcak çikolata",
                            ImageUrl = "images/products/sıcakçiko.png",
                            Name = "Hot Chocolate",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("FoodECommerce.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("FoodECommerce.Models.Product", b =>
                {
                    b.HasOne("FoodECommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
